CREATE TABLE employee(ID INT(11) NOT NULL, EMPLOYEENAME VARCHAR(50) NOT NULL, EMPLOYEEDESIGNATION VARCHAR(100) NOT NULL, PRIMARY KEY(ID));
CREATE TABLE project(ID INT(11) NOT NULL, PROJECTNAME VARCHAR(100) NOT NULL, DURATION INT(10) NOT NULL, MEMBERS INT(11) NOT NULL, PRIMARY KEY(ID), FOREIGN KEY(MEMBERS) REFERENCES employee(ID) ON DELETE CASCADE);
